// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:bloc_clean_template/features/auth/data/models/dtos/user_dto.dart';
import 'package:hive_ce/hive_ce.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(UserDtoAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(UserDtoAdapter());
  }
}
